### ISSUE TITLE
total vote limit

### ISSUE THREAD

**Issue by d0x2f** [d0x2f/retrograde.js#14]

**Comment by chrisleekr** [comment]
I personally liked to vote for multiple cards.
Maybe good idea to be able to configure allow voting every card or number of vote limit.

**Comment by d0x2f** [comment]
I think a vote limit is more useful during a live retro on a whiteboard as a way to limit the amount of time taken to place votes.
An online tool like this one mitigates the problem becasue voting no longer gets in anyones way and doesn't block the meeting from continuing.
I'd be happy to reopen this issue if it becomes a popular request.
