### ISSUE TITLE
Request - Ice break

### ISSUE THREAD

**Issue by RMCampos** [d0x2f/retrograde.js#162]
How about some ice break ideas? Maybe one card at the top with one question?

**Comment by d0x2f** [comment]
Cool idea!

My suggestion on how to implement this would be to add a flag to cards that marks it as a prompt.

Only the board owner should be able to set that flag.

For cards where this flag is set, pin them to the top of the column with prominent styling.

Much like regular cards, only board owner should see the `delete` and `edit` buttons on the card, and they should have voting disabled on them altogether (i.e. no voting buttons or numbers visible to anyone).

What do you think?

**Comment by RMCampos** [comment]
I'm thinking of enabling an input text with the ice-breaking question. In the splash screen, at the more setting option, show an input. And if it has some text, show it on the board, at to top of the columns. Something like this:

Splash screen image:
![image](https://user-images.githubusercontent.com/2219519/167712576-bf9cb81b-dcc9-454b-8915-2cf4571a6d77.png)

Board example:
![image](https://user-images.githubusercontent.com/2219519/167715177-dcb89593-df92-4897-9840-4780cd153e52.png)

**Comment by d0x2f** [comment]
Oh yeah nice, that looks good! :+1:

**Comment by d0x2f** [comment]
Merged and live! Thanks @RMCampos
