### ISSUE TITLE
Request - pt_BR (Brazil) translation

### ISSUE THREAD

**Issue by RMCampos** [d0x2f/retrograde.js#163]
I can work on this. How can I get started? 

Thanks.

**Comment by d0x2f** [comment]
Hi @RMCampos,

You can copy one of the other language files such as `en.json` to `pt_BR.json` in the [lang](https://github.com/d0x2f/retrograde.js/tree/master/src/lang) folder and translate each of the lines.

Once you've finished the file submit a merge request and I'll hook it all up.

Thanks so much!

**Comment by d0x2f** [comment]
a good example to follow: https://github.com/d0x2f/retrograde.js/pull/157/files

**Comment by d0x2f** [comment]
This is live now, thanks again!

If you ever have any changes or tweaks to make, feel free to submit another PR any time.

**Comment by RMCampos** [comment]
Thank you @d0x2f
