### ISSUE TITLE
Feature request: Account

### ISSUE THREAD

**Issue by chrisleekr** [d0x2f/retrograde.js#24]
It would be good if you can log in and 
- manage my board - create (public/private), edit, delete, archive, upload board logo
- create/invite team
- see previous participated retro boards

**Comment by d0x2f** [comment]
I'm making a decision not to support accounts.
I think it's too complicated a feature with little to no benefit.
To address the things listed in your description:
- create private boards - all boards are essentially private with the hash in the url effectively being a password to entry.
- edit/delete boards - the board owner can edit and delete all aspects of the board.
- archive board - I think the ability to disable new cards and voting is tantamount to archival.
- create/invite team - Invite emails would be a welcome feature not reliant on having an account.
- previous boards - A list of previously visited boards is available on the splash page.
