### ISSUE TITLE
Bug: Can create empty card

### ISSUE THREAD

**Issue by chrisleekr** [d0x2f/retrograde.js#45]
I can create empty card, and it shows 0 in card

<img width="1280" alt="Screen Shot 2020-02-03 at 23 28 15" src="https://user-images.githubusercontent.com/5715919/73661135-e790d700-46dc-11ea-919f-2bb7184bfc55.png">

**Comment by d0x2f** [comment]
0 is the number of votes.
But yeah you're right, there's no point in an empty card.
